services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql_db'
    environment:
      - 'MYSQL_DATABASE=forum_db'
      - 'MYSQL_PASSWORD=dev@password'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=dev'
    ports:
      - '3306:3306'
